### ISSUE TITLE
Add a user-agent to HTTP requests

### ISSUE THREAD

**Issue by natarii** [Rast1234/SyncFaction#2]
Please identify HTTP requests made by SyncFaction with a User-Agent header.

**Comment by Rast1234** [comment]
hey, no problem, i'll add it with next release. i hope it's not urgent? don't want to disturb players with an update with no new features just for an added header

**Comment by natarii** [comment]
Not urgent :)

**Comment by Rast1234** [comment]
added in this version: https://github.com/Rast1234/SyncFaction/releases/tag/v8
reopen if it doesn't work or need specific header value. currently it's just `SyncFaction`
